// <auto-generated />
using System;
using BookWarms.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookWarms.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250818104555_AddLibraryAndReviewsSeed")]
    partial class AddLibraryAndReviewsSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookWarms.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "F. Scott Fitzgerald",
                            Description = "A novel set in the Roaring Twenties.",
                            Genre = "Classic",
                            PageCount = 180,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 2,
                            Author = "George Orwell",
                            Description = "A story about a totalitarian regime.",
                            Genre = "Dystopian",
                            PageCount = 328,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Jane Austen",
                            Description = "A witty exploration of manners, morality, and love.",
                            Genre = "Romance",
                            PageCount = 279,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Harper Lee",
                            Description = "A young girl's perspective on racial injustice in the Deep South.",
                            Genre = "Classic",
                            PageCount = 324,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Herman Melville",
                            Description = "The obsessive quest for revenge against the white whale.",
                            Genre = "Adventure",
                            PageCount = 635,
                            Title = "Moby Dick"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Leo Tolstoy",
                            Description = "A sweeping narrative of love and conflict during Napoleon's invasion of Russia.",
                            Genre = "Historical",
                            PageCount = 1225,
                            Title = "War and Peace"
                        },
                        new
                        {
                            Id = 7,
                            Author = "J.R.R. Tolkien",
                            Description = "Bilbo Baggins' journey to help dwarves reclaim their homeland.",
                            Genre = "Fantasy",
                            PageCount = 310,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 8,
                            Author = "J.R.R. Tolkien",
                            Description = "The first part of the epic quest to destroy the One Ring.",
                            Genre = "Fantasy",
                            PageCount = 423,
                            Title = "The Fellowship of the Ring"
                        },
                        new
                        {
                            Id = 9,
                            Author = "J.R.R. Tolkien",
                            Description = "The fellowship is broken, and the war for Middle-earth begins.",
                            Genre = "Fantasy",
                            PageCount = 352,
                            Title = "The Two Towers"
                        },
                        new
                        {
                            Id = 10,
                            Author = "J.R.R. Tolkien",
                            Description = "The final battle for Middle-earth.",
                            Genre = "Fantasy",
                            PageCount = 416,
                            Title = "The Return of the King"
                        },
                        new
                        {
                            Id = 11,
                            Author = "J.K. Rowling",
                            Description = "A boy discovers he is a wizard and attends Hogwarts.",
                            Genre = "Fantasy",
                            PageCount = 309,
                            Title = "Harry Potter and the Sorcerer's Stone"
                        },
                        new
                        {
                            Id = 12,
                            Author = "J.K. Rowling",
                            Description = "A mysterious chamber holds a deadly secret.",
                            Genre = "Fantasy",
                            PageCount = 341,
                            Title = "Harry Potter and the Chamber of Secrets"
                        },
                        new
                        {
                            Id = 13,
                            Author = "J.K. Rowling",
                            Description = "A dangerous prisoner escapes from Azkaban.",
                            Genre = "Fantasy",
                            PageCount = 435,
                            Title = "Harry Potter and the Prisoner of Azkaban"
                        },
                        new
                        {
                            Id = 14,
                            Author = "J.K. Rowling",
                            Description = "The Triwizard Tournament brings new dangers.",
                            Genre = "Fantasy",
                            PageCount = 734,
                            Title = "Harry Potter and the Goblet of Fire"
                        },
                        new
                        {
                            Id = 15,
                            Author = "J.K. Rowling",
                            Description = "Dark forces rise, and Dumbledore's Army is formed.",
                            Genre = "Fantasy",
                            PageCount = 870,
                            Title = "Harry Potter and the Order of the Phoenix"
                        },
                        new
                        {
                            Id = 16,
                            Author = "J.K. Rowling",
                            Description = "Secrets of Voldemort's past come to light.",
                            Genre = "Fantasy",
                            PageCount = 652,
                            Title = "Harry Potter and the Half-Blood Prince"
                        },
                        new
                        {
                            Id = 17,
                            Author = "J.K. Rowling",
                            Description = "The final battle between Harry and Voldemort.",
                            Genre = "Fantasy",
                            PageCount = 759,
                            Title = "Harry Potter and the Deathly Hallows"
                        },
                        new
                        {
                            Id = 18,
                            Author = "J.D. Salinger",
                            Description = "Holden Caulfield's story of teenage rebellion.",
                            Genre = "Classic",
                            PageCount = 277,
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            Id = 19,
                            Author = "Paulo Coelho",
                            Description = "A shepherd's journey to find his personal legend.",
                            Genre = "Fiction",
                            PageCount = 208,
                            Title = "The Alchemist"
                        },
                        new
                        {
                            Id = 20,
                            Author = "Aldous Huxley",
                            Description = "A futuristic world shaped by genetic engineering.",
                            Genre = "Dystopian",
                            PageCount = 288,
                            Title = "Brave New World"
                        },
                        new
                        {
                            Id = 21,
                            Author = "Fyodor Dostoevsky",
                            Description = "A psychological exploration of morality and guilt.",
                            Genre = "Classic",
                            PageCount = 671,
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            Id = 22,
                            Author = "Leo Tolstoy",
                            Description = "A tragic love affair in 19th century Russia.",
                            Genre = "Romance",
                            PageCount = 864,
                            Title = "Anna Karenina"
                        },
                        new
                        {
                            Id = 23,
                            Author = "Fyodor Dostoevsky",
                            Description = "A profound exploration of faith, doubt, and morality.",
                            Genre = "Philosophical",
                            PageCount = 796,
                            Title = "The Brothers Karamazov"
                        },
                        new
                        {
                            Id = 24,
                            Author = "Victor Hugo",
                            Description = "A sweeping story of redemption and revolution in France.",
                            Genre = "Historical",
                            PageCount = 1232,
                            Title = "Les Misérables"
                        },
                        new
                        {
                            Id = 25,
                            Author = "Alexandre Dumas",
                            Description = "A tale of betrayal, revenge, and justice.",
                            Genre = "Adventure",
                            PageCount = 1276,
                            Title = "The Count of Monte Cristo"
                        },
                        new
                        {
                            Id = 26,
                            Author = "Bram Stoker",
                            Description = "The iconic vampire story.",
                            Genre = "Horror",
                            PageCount = 418,
                            Title = "Dracula"
                        },
                        new
                        {
                            Id = 27,
                            Author = "Mary Shelley",
                            Description = "A scientist creates life with tragic consequences.",
                            Genre = "Horror",
                            PageCount = 280,
                            Title = "Frankenstein"
                        },
                        new
                        {
                            Id = 28,
                            Author = "Charlotte Brontë",
                            Description = "A governess's journey to love and independence.",
                            Genre = "Classic",
                            PageCount = 532,
                            Title = "Jane Eyre"
                        },
                        new
                        {
                            Id = 29,
                            Author = "Emily Brontë",
                            Description = "A dark tale of passion and revenge on the Yorkshire moors.",
                            Genre = "Classic",
                            PageCount = 416,
                            Title = "Wuthering Heights"
                        },
                        new
                        {
                            Id = 30,
                            Author = "Oscar Wilde",
                            Description = "A man remains young while his portrait ages.",
                            Genre = "Philosophical",
                            PageCount = 254,
                            Title = "The Picture of Dorian Gray"
                        },
                        new
                        {
                            Id = 31,
                            Author = "Charles Dickens",
                            Description = "A story of love and sacrifice set during the French Revolution.",
                            Genre = "Historical",
                            PageCount = 489,
                            Title = "A Tale of Two Cities"
                        },
                        new
                        {
                            Id = 32,
                            Author = "Charles Dickens",
                            Description = "The journey of an orphan named Pip towards self-discovery.",
                            Genre = "Classic",
                            PageCount = 505,
                            Title = "Great Expectations"
                        },
                        new
                        {
                            Id = 33,
                            Author = "Charles Dickens",
                            Description = "A semi-autobiographical tale of growth and perseverance.",
                            Genre = "Classic",
                            PageCount = 882,
                            Title = "David Copperfield"
                        },
                        new
                        {
                            Id = 34,
                            Author = "Charles Dickens",
                            Description = "The hardships of an orphan in Victorian London.",
                            Genre = "Classic",
                            PageCount = 554,
                            Title = "Oliver Twist"
                        },
                        new
                        {
                            Id = 35,
                            Author = "Ernest Hemingway",
                            Description = "An aging fisherman's struggle with a giant marlin.",
                            Genre = "Fiction",
                            PageCount = 127,
                            Title = "The Old Man and the Sea"
                        },
                        new
                        {
                            Id = 36,
                            Author = "Ernest Hemingway",
                            Description = "A tale of love and sacrifice during the Spanish Civil War.",
                            Genre = "Historical",
                            PageCount = 480,
                            Title = "For Whom the Bell Tolls"
                        },
                        new
                        {
                            Id = 37,
                            Author = "Ernest Hemingway",
                            Description = "A tragic romance set in World War I.",
                            Genre = "Romance",
                            PageCount = 332,
                            Title = "A Farewell to Arms"
                        },
                        new
                        {
                            Id = 38,
                            Author = "Ernest Hemingway",
                            Description = "A group of expatriates in post-war Europe.",
                            Genre = "Fiction",
                            PageCount = 251,
                            Title = "The Sun Also Rises"
                        },
                        new
                        {
                            Id = 39,
                            Author = "Joseph Heller",
                            Description = "The absurdities of war through the eyes of a bomber pilot.",
                            Genre = "Satire",
                            PageCount = 453,
                            Title = "Catch-22"
                        },
                        new
                        {
                            Id = 40,
                            Author = "Kurt Vonnegut",
                            Description = "A soldier's journey through time and space after WWII.",
                            Genre = "Science Fiction",
                            PageCount = 275,
                            Title = "Slaughterhouse-Five"
                        },
                        new
                        {
                            Id = 41,
                            Author = "John Steinbeck",
                            Description = "A family's migration during the Great Depression.",
                            Genre = "Historical",
                            PageCount = 464,
                            Title = "The Grapes of Wrath"
                        },
                        new
                        {
                            Id = 42,
                            Author = "John Steinbeck",
                            Description = "The tragic story of two migrant workers during the Depression.",
                            Genre = "Classic",
                            PageCount = 187,
                            Title = "Of Mice and Men"
                        },
                        new
                        {
                            Id = 43,
                            Author = "John Steinbeck",
                            Description = "A multigenerational story of love, jealousy, and betrayal.",
                            Genre = "Fiction",
                            PageCount = 601,
                            Title = "East of Eden"
                        },
                        new
                        {
                            Id = 44,
                            Author = "John Steinbeck",
                            Description = "A slice of life in a small California community.",
                            Genre = "Fiction",
                            PageCount = 208,
                            Title = "Cannery Row"
                        },
                        new
                        {
                            Id = 45,
                            Author = "Miguel de Cervantes",
                            Description = "The adventures of a delusional knight and his loyal squire.",
                            Genre = "Classic",
                            PageCount = 982,
                            Title = "Don Quixote"
                        },
                        new
                        {
                            Id = 46,
                            Author = "Dante Alighieri",
                            Description = "A journey through Hell, Purgatory, and Paradise.",
                            Genre = "Epic Poetry",
                            PageCount = 798,
                            Title = "The Divine Comedy"
                        },
                        new
                        {
                            Id = 47,
                            Author = "Homer",
                            Description = "Odysseus' long journey home from the Trojan War.",
                            Genre = "Epic Poetry",
                            PageCount = 541,
                            Title = "The Odyssey"
                        },
                        new
                        {
                            Id = 48,
                            Author = "Homer",
                            Description = "The final weeks of the Trojan War.",
                            Genre = "Epic Poetry",
                            PageCount = 683,
                            Title = "The Iliad"
                        },
                        new
                        {
                            Id = 49,
                            Author = "Marcus Aurelius",
                            Description = "The Stoic reflections of a Roman emperor.",
                            Genre = "Philosophy",
                            PageCount = 254,
                            Title = "Meditations"
                        },
                        new
                        {
                            Id = 50,
                            Author = "Niccolò Machiavelli",
                            Description = "A treatise on political power and leadership.",
                            Genre = "Political",
                            PageCount = 140,
                            Title = "The Prince"
                        },
                        new
                        {
                            Id = 51,
                            Author = "Friedrich Nietzsche",
                            Description = "A philosophical novel introducing the idea of the Übermensch.",
                            Genre = "Philosophy",
                            PageCount = 327,
                            Title = "Thus Spoke Zarathustra"
                        },
                        new
                        {
                            Id = 52,
                            Author = "Friedrich Nietzsche",
                            Description = "A critique of traditional morality.",
                            Genre = "Philosophy",
                            PageCount = 240,
                            Title = "Beyond Good and Evil"
                        },
                        new
                        {
                            Id = 53,
                            Author = "Sun Tzu",
                            Description = "Ancient Chinese military strategy and tactics.",
                            Genre = "Strategy",
                            PageCount = 273,
                            Title = "The Art of War"
                        },
                        new
                        {
                            Id = 54,
                            Author = "Charles Darwin",
                            Description = "The foundation of evolutionary biology.",
                            Genre = "Science",
                            PageCount = 502,
                            Title = "On the Origin of Species"
                        },
                        new
                        {
                            Id = 55,
                            Author = "Rachel Carson",
                            Description = "An environmental science book that sparked change.",
                            Genre = "Science",
                            PageCount = 378,
                            Title = "Silent Spring"
                        },
                        new
                        {
                            Id = 56,
                            Author = "Stephen Hawking",
                            Description = "An exploration of cosmology and black holes.",
                            Genre = "Science",
                            PageCount = 212,
                            Title = "A Brief History of Time"
                        },
                        new
                        {
                            Id = 57,
                            Author = "Richard Dawkins",
                            Description = "An influential work on evolutionary biology.",
                            Genre = "Science",
                            PageCount = 360,
                            Title = "The Selfish Gene"
                        },
                        new
                        {
                            Id = 58,
                            Author = "Yuval Noah Harari",
                            Description = "A sweeping history of humanity from ancient times to today.",
                            Genre = "History",
                            PageCount = 443,
                            Title = "Sapiens: A Brief History of Humankind"
                        },
                        new
                        {
                            Id = 59,
                            Author = "Yuval Noah Harari",
                            Description = "Speculations about the future of humanity.",
                            Genre = "History",
                            PageCount = 450,
                            Title = "Homo Deus: A Brief History of Tomorrow"
                        },
                        new
                        {
                            Id = 60,
                            Author = "Yuval Noah Harari",
                            Description = "Insights into the modern challenges of our world.",
                            Genre = "Nonfiction",
                            PageCount = 372,
                            Title = "21 Lessons for the 21st Century"
                        },
                        new
                        {
                            Id = 61,
                            Author = "Daniel Kahneman",
                            Description = "An analysis of the two systems that drive our thinking.",
                            Genre = "Psychology",
                            PageCount = 499,
                            Title = "Thinking, Fast and Slow"
                        },
                        new
                        {
                            Id = 62,
                            Author = "Viktor E. Frankl",
                            Description = "A Holocaust survivor's reflections on purpose and resilience.",
                            Genre = "Psychology",
                            PageCount = 200,
                            Title = "Man's Search for Meaning"
                        },
                        new
                        {
                            Id = 63,
                            Author = "Cormac McCarthy",
                            Description = "A father and son's journey in a desolate world.",
                            Genre = "Post-Apocalyptic",
                            PageCount = 287,
                            Title = "The Road"
                        },
                        new
                        {
                            Id = 64,
                            Author = "Cormac McCarthy",
                            Description = "A violent tale set in the 19th-century American West.",
                            Genre = "Western",
                            PageCount = 351,
                            Title = "Blood Meridian"
                        },
                        new
                        {
                            Id = 65,
                            Author = "Cormac McCarthy",
                            Description = "A brutal chase after stolen drug money.",
                            Genre = "Thriller",
                            PageCount = 309,
                            Title = "No Country for Old Men"
                        },
                        new
                        {
                            Id = 66,
                            Author = "Cormac McCarthy",
                            Description = "A young cowboy's journey into Mexico.",
                            Genre = "Western",
                            PageCount = 302,
                            Title = "All the Pretty Horses"
                        },
                        new
                        {
                            Id = 67,
                            Author = "Stephen King",
                            Description = "A haunted hotel turns a man into a danger to his family.",
                            Genre = "Horror",
                            PageCount = 447,
                            Title = "The Shining"
                        },
                        new
                        {
                            Id = 68,
                            Author = "Stephen King",
                            Description = "A group of friends face an ancient evil in their town.",
                            Genre = "Horror",
                            PageCount = 1138,
                            Title = "It"
                        },
                        new
                        {
                            Id = 69,
                            Author = "Stephen King",
                            Description = "An author is held captive by a deranged fan.",
                            Genre = "Thriller",
                            PageCount = 320,
                            Title = "Misery"
                        },
                        new
                        {
                            Id = 70,
                            Author = "Stephen King",
                            Description = "A deadly plague leads to a battle between good and evil.",
                            Genre = "Post-Apocalyptic",
                            PageCount = 1153,
                            Title = "The Stand"
                        },
                        new
                        {
                            Id = 71,
                            Author = "Stephen King",
                            Description = "A burial ground with the power to resurrect the dead.",
                            Genre = "Horror",
                            PageCount = 374,
                            Title = "Pet Sematary"
                        },
                        new
                        {
                            Id = 72,
                            Author = "Stephen King",
                            Description = "A bullied girl develops terrifying powers.",
                            Genre = "Horror",
                            PageCount = 199,
                            Title = "Carrie"
                        },
                        new
                        {
                            Id = 73,
                            Author = "Andy Weir",
                            Description = "An astronaut stranded on Mars must survive against all odds.",
                            Genre = "Science Fiction",
                            PageCount = 369,
                            Title = "The Martian"
                        },
                        new
                        {
                            Id = 74,
                            Author = "Andy Weir",
                            Description = "A lone astronaut's mission to save humanity.",
                            Genre = "Science Fiction",
                            PageCount = 496,
                            Title = "Project Hail Mary"
                        },
                        new
                        {
                            Id = 75,
                            Author = "Andy Weir",
                            Description = "A heist on the Moon goes wrong.",
                            Genre = "Science Fiction",
                            PageCount = 305,
                            Title = "Artemis"
                        },
                        new
                        {
                            Id = 76,
                            Author = "Frank Herbert",
                            Description = "The epic saga of politics, prophecy, and sandworms.",
                            Genre = "Science Fiction",
                            PageCount = 688,
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 77,
                            Author = "Frank Herbert",
                            Description = "The sequel to Dune, exploring Paul Atreides' reign.",
                            Genre = "Science Fiction",
                            PageCount = 336,
                            Title = "Dune Messiah"
                        },
                        new
                        {
                            Id = 78,
                            Author = "Frank Herbert",
                            Description = "The struggle for control of Arrakis continues.",
                            Genre = "Science Fiction",
                            PageCount = 408,
                            Title = "Children of Dune"
                        },
                        new
                        {
                            Id = 79,
                            Author = "Frank Herbert",
                            Description = "A millennia-spanning tale of transformation and tyranny.",
                            Genre = "Science Fiction",
                            PageCount = 496,
                            Title = "God Emperor of Dune"
                        },
                        new
                        {
                            Id = 80,
                            Author = "Frank Herbert",
                            Description = "Political intrigue and rebellion on Arrakis.",
                            Genre = "Science Fiction",
                            PageCount = 480,
                            Title = "Heretics of Dune"
                        },
                        new
                        {
                            Id = 81,
                            Author = "Frank Herbert",
                            Description = "The Bene Gesserit's fight for survival.",
                            Genre = "Science Fiction",
                            PageCount = 464,
                            Title = "Chapterhouse: Dune"
                        },
                        new
                        {
                            Id = 82,
                            Author = "William Gibson",
                            Description = "A washed-up hacker hired for a final job.",
                            Genre = "Cyberpunk",
                            PageCount = 271,
                            Title = "Neuromancer"
                        },
                        new
                        {
                            Id = 83,
                            Author = "William Gibson",
                            Description = "Corporate intrigue and cyberspace adventures.",
                            Genre = "Cyberpunk",
                            PageCount = 246,
                            Title = "Count Zero"
                        },
                        new
                        {
                            Id = 84,
                            Author = "William Gibson",
                            Description = "The conclusion to Gibson's Sprawl trilogy.",
                            Genre = "Cyberpunk",
                            PageCount = 288,
                            Title = "Mona Lisa Overdrive"
                        },
                        new
                        {
                            Id = 85,
                            Author = "Neal Stephenson",
                            Description = "A pizza delivery man/hacker uncovers a deadly virus.",
                            Genre = "Cyberpunk",
                            PageCount = 440,
                            Title = "Snow Crash"
                        },
                        new
                        {
                            Id = 86,
                            Author = "Neal Stephenson",
                            Description = "A complex tale of codebreakers and treasure hunters.",
                            Genre = "Historical Fiction",
                            PageCount = 918,
                            Title = "Cryptonomicon"
                        },
                        new
                        {
                            Id = 87,
                            Author = "Neal Stephenson",
                            Description = "Humanity fights to survive after the moon shatters.",
                            Genre = "Science Fiction",
                            PageCount = 880,
                            Title = "Seveneves"
                        },
                        new
                        {
                            Id = 88,
                            Author = "Neal Stephenson",
                            Description = "A monk-like scholar is thrust into a cosmic mystery.",
                            Genre = "Science Fiction",
                            PageCount = 935,
                            Title = "Anathem"
                        },
                        new
                        {
                            Id = 89,
                            Author = "Ursula K. Le Guin",
                            Description = "A diplomat's mission to a world with ambisexual inhabitants.",
                            Genre = "Science Fiction",
                            PageCount = 304,
                            Title = "The Left Hand of Darkness"
                        },
                        new
                        {
                            Id = 90,
                            Author = "Ursula K. Le Guin",
                            Description = "A young wizard's journey of self-discovery.",
                            Genre = "Fantasy",
                            PageCount = 183,
                            Title = "A Wizard of Earthsea"
                        },
                        new
                        {
                            Id = 91,
                            Author = "Ursula K. Le Guin",
                            Description = "A priestess meets the wizard Ged in an ancient tomb.",
                            Genre = "Fantasy",
                            PageCount = 180,
                            Title = "The Tombs of Atuan"
                        },
                        new
                        {
                            Id = 92,
                            Author = "Ursula K. Le Guin",
                            Description = "Ged and a prince confront a threat to magic itself.",
                            Genre = "Fantasy",
                            PageCount = 246,
                            Title = "The Farthest Shore"
                        },
                        new
                        {
                            Id = 93,
                            Author = "Ursula K. Le Guin",
                            Description = "A quiet but powerful continuation of Earthsea's story.",
                            Genre = "Fantasy",
                            PageCount = 256,
                            Title = "Tehanu"
                        },
                        new
                        {
                            Id = 94,
                            Author = "Ursula K. Le Guin",
                            Description = "A physicist bridges two very different worlds.",
                            Genre = "Science Fiction",
                            PageCount = 387,
                            Title = "The Dispossessed"
                        },
                        new
                        {
                            Id = 95,
                            Author = "Isaac Asimov",
                            Description = "A mathematician predicts the fall of a galactic empire.",
                            Genre = "Science Fiction",
                            PageCount = 255,
                            Title = "Foundation"
                        },
                        new
                        {
                            Id = 96,
                            Author = "Isaac Asimov",
                            Description = "The Foundation faces new challenges as it grows.",
                            Genre = "Science Fiction",
                            PageCount = 282,
                            Title = "Foundation and Empire"
                        },
                        new
                        {
                            Id = 97,
                            Author = "Isaac Asimov",
                            Description = "The search for the mysterious Second Foundation.",
                            Genre = "Science Fiction",
                            PageCount = 240,
                            Title = "Second Foundation"
                        },
                        new
                        {
                            Id = 98,
                            Author = "Isaac Asimov",
                            Description = "A collection of short stories exploring robotics.",
                            Genre = "Science Fiction",
                            PageCount = 253,
                            Title = "I, Robot"
                        },
                        new
                        {
                            Id = 99,
                            Author = "Isaac Asimov",
                            Description = "A detective and his robot partner investigate a murder.",
                            Genre = "Science Fiction",
                            PageCount = 270,
                            Title = "The Caves of Steel"
                        },
                        new
                        {
                            Id = 100,
                            Author = "Isaac Asimov",
                            Description = "A detective investigates a murder on a distant world.",
                            Genre = "Science Fiction",
                            PageCount = 288,
                            Title = "The Naked Sun"
                        });
                });

            modelBuilder.Entity("BookWarms.Models.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("ShelfType")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Libraries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            ShelfType = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            ShelfType = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            BookId = 3,
                            ShelfType = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            BookId = 4,
                            ShelfType = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            BookId = 5,
                            ShelfType = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            BookId = 6,
                            ShelfType = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            BookId = 7,
                            ShelfType = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 8,
                            BookId = 8,
                            ShelfType = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 9,
                            BookId = 9,
                            ShelfType = 2,
                            UserId = 5
                        },
                        new
                        {
                            Id = 10,
                            BookId = 10,
                            ShelfType = 0,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("BookWarms.Models.ReadingStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BooksRead")
                        .HasColumnType("int");

                    b.Property<int>("PagesRead")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ReadingStats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            BooksRead = 1,
                            PagesRead = 279,
                            UserId = 2,
                            Year = 2025
                        },
                        new
                        {
                            Id = 3,
                            BooksRead = 1,
                            PagesRead = 324,
                            UserId = 3,
                            Year = 2025
                        },
                        new
                        {
                            Id = 1,
                            BooksRead = 2,
                            PagesRead = 508,
                            UserId = 1,
                            Year = 2025
                        });
                });

            modelBuilder.Entity("BookWarms.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("LibraryId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.ToTable("Reviews", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LibraryId = 1,
                            Rating = 4,
                            ReviewText = "A delightful read!"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LibraryId = 2,
                            Rating = 5,
                            ReviewText = "A powerful story about justice."
                        },
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LibraryId = 1,
                            Rating = 5,
                            ReviewText = "A timeless classic!"
                        });
                });

            modelBuilder.Entity("BookWarms.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "krisistoyanova2008@gmail.com",
                            Username = "Admin: Kristiana Stoyanova"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ivan@example.com",
                            Username = "Ivan Petrov"
                        },
                        new
                        {
                            Id = 3,
                            Email = "maria@example.com",
                            Username = "Maria Georgieva"
                        },
                        new
                        {
                            Id = 4,
                            Email = "petar@example.com",
                            Username = "Petar Dimitrov"
                        },
                        new
                        {
                            Id = 5,
                            Email = "elena@example.com",
                            Username = "Elena Koleva"
                        },
                        new
                        {
                            Id = 6,
                            Email = "stoyan@example.com",
                            Username = "Stoyan Stoyanov"
                        },
                        new
                        {
                            Id = 7,
                            Email = "katerina@example.com",
                            Username = "Katerina Todorova"
                        },
                        new
                        {
                            Id = 8,
                            Email = "nikolay@example.com",
                            Username = "Nikolay Ivanov"
                        },
                        new
                        {
                            Id = 9,
                            Email = "hristo@example.com",
                            Username = "Hristo Hristov"
                        },
                        new
                        {
                            Id = 10,
                            Email = "desislava@example.com",
                            Username = "Desislava Petrova"
                        },
                        new
                        {
                            Id = 11,
                            Email = "dimitar@example.com",
                            Username = "Dimitar Dimitrov"
                        },
                        new
                        {
                            Id = 12,
                            Email = "viktoria@example.com",
                            Username = "Viktoria Mihaylova"
                        },
                        new
                        {
                            Id = 13,
                            Email = "aleksandar@example.com",
                            Username = "Aleksandar Angelov"
                        },
                        new
                        {
                            Id = 14,
                            Email = "yana@example.com",
                            Username = "Yana Stoyanova"
                        },
                        new
                        {
                            Id = 15,
                            Email = "georgi@example.com",
                            Username = "Georgi Georgiev"
                        });
                });

            modelBuilder.Entity("BookWarms.Models.Library", b =>
                {
                    b.HasOne("BookWarms.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookWarms.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookWarms.Models.ReadingStat", b =>
                {
                    b.HasOne("BookWarms.Models.Library", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookWarms.Models.Review", b =>
                {
                    b.HasOne("BookWarms.Models.Library", "Library")
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });
#pragma warning restore 612, 618
        }
    }
}
